server.port=8080

solon.app.name=wqs-admin
solon.app.group=com.wqs

# 数据库配置
wqs.db.url=jdbc:mysql://120.53.227.18:3306/wqs_admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
wqs.db.username=root
wqs.db.password=Jetox8087.
wqs.db.driverClassName=com.mysql.cj.jdbc.Driver

# Redis 配置
wqs.redis.server=127.0.0.1:6379
# wqs.redis.password=
wqs.redis.db=0
wqs.redis.maxTotal=200

# MyBatis 配置
mybatis.db1.scan=com.wqs.admin.mapper
mybatis.plus.configuration.mapUnderscoreToCamelCase=true
mybatis.plus.configuration.logImpl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.plus.global-config.db-config.logic-delete-field=deleted
mybatis.plus.global-config.db-config.logic-delete-value=1
mybatis.plus.global-config.db-config.logic-not-delete-value=0

# Sa-Token 配置
sa-token.token-name=wqs-admin-token
sa-token.timeout=2592000
sa-token.activity-timeout=-1
sa-token.is-concurrent=true
sa-token.is-share=false
sa-token.token-style=uuid
sa-token.is-log=false
